const grid=document.querySelector('#catalog');let category='Todos';const search=document.querySelector('#search');const normalize=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const externalArrowIcon='<svg viewBox="0 0 24 24" width="16" height="16" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M7 17 17 7"/><path d="M7 7h10v10"/></svg>';
function card(p,featured=false){const a=document.createElement('a');a.className=featured?'card featured-card':'card';a.href='produto.html?id='+p.id;const media=document.createElement('div');media.className='card-media';const img=document.createElement('img');img.src=p.image;img.alt=p.name;img.width=500;img.height=500;img.loading='lazy';media.append(img);if(featured){const badge=document.createElement('span');badge.className='card-badge';badge.textContent='Em destaque';media.append(badge)}const arrow=document.createElement('span');arrow.className='card-arrow';arrow.setAttribute('aria-hidden','true');arrow.innerHTML=externalArrowIcon;media.append(arrow);const info=document.createElement('div');info.className='card-info';const type=document.createElement('span');type.className='eyebrow';type.textContent=p.category;const name=document.createElement('h3');name.textContent=p.name;const price=document.createElement('p');price.className='price';price.textContent=money(p.price);info.append(type,name);if(featured){const ref=document.createElement("p");ref.className="reference-price";const old=document.createElement("s");old.textContent=money(Math.round(p.price*110)/100);ref.append(old);info.append(ref)}info.append(price);a.append(media,info);return a}
function showProducts(q=search.value){const results=window.products.filter(p=>(category==='Todos'||p.category===category)&&normalize(p.name+' '+p.category).includes(normalize(q.trim())));grid.replaceChildren(...results.map(p=>card(p)));window.observeMotion?.(grid.querySelectorAll(".card"));document.querySelector('#empty').hidden=results.length>0;document.querySelector('#search-status').textContent=q.trim()?`${results.length} resultado(s) para “${q.trim()}”`:'';return results.map(({id,name,price})=>({id,name,price}))}
document.querySelector('#featured').replaceChildren(...['ferrero','rosas','cafe','coracao'].map(id=>card(window.products.find(p=>p.id===id),true)));
document.querySelectorAll('[data-category]').forEach(button=>button.onclick=()=>{category=button.dataset.category;document.querySelectorAll('[data-category]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));showProducts()});document.addEventListener('catalog-search',()=>showProducts());
document.querySelector('#clear-search').onclick=()=>{search.value='';document.querySelector('[data-category="Todos"]').click()};
const initialQuery=new URLSearchParams(location.search).get('q');if(initialQuery){search.value=initialQuery;expandSearch(true)}showProducts();
const slides=[...document.querySelectorAll('.slide')];let current=0;
function showSlide(index){current=(index+slides.length)%slides.length;slides.forEach((slide,i)=>{slide.hidden=i!==current;slide.setAttribute('aria-hidden',String(i!==current))});}
const bannerTimer=setInterval(()=>{if(!document.hidden)showSlide(current+1)},5000);
window.addEventListener('pagehide',()=>clearInterval(bannerTimer),{once:true});
window.observeMotion?.(document.querySelectorAll('.card,.section-heading,.personalize,.hero'));
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'search_products',description:'Pesquisar e mostrar produtos no catálogo.',inputSchema:{type:'object',properties:{query:{type:'string'}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(typeof input?.query!=='string')throw Error('Informe um texto.');search.value=input.query;document.querySelector('[data-category="Todos"]').click();expandSearch(true);document.querySelector('#catalogo').scrollIntoView();return {products:showProducts(input.query)}}})).catch(()=>{})}catch{}}
