const homePage=!!document.querySelector('.home-main'),base=homePage?'':'index.html';
const externalArrowSvg='<svg class="link-icon" viewBox="0 0 24 24" width="15" height="15" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M7 17 17 7"/><path d="M7 7h10v10"/></svg>';
document.querySelector('header').innerHTML=`<div class="header-inner"><a class="brand" href="${base}#home" aria-label="Home"><img class="logo" src="assets/logo.svg" alt="Logo da loja" width="112" height="45"></a><nav class="main-nav" aria-label="Navegação principal"><a href="${base}#home">Home</a><a href="${base}#mais-vendidos">Mais vendidos</a><a href="${base}#catalogo">Catálogo</a><a href="${base}#personalize">Personalize</a></nav><form class="search-shell" role="search"><label class="sr-only" for="search">Pesquisar produtos</label><input id="search" type="search" placeholder="Qual presente você procura?" autocomplete="off" disabled><button class="search-toggle" type="button" aria-label="Abrir pesquisa" aria-expanded="false" aria-controls="search"><svg width="21" height="21" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><circle cx="10.5" cy="10.5" r="6.8"/><path d="m16 16 5 5"/></svg></button></form></div>`;
const shell=document.querySelector('.search-shell'),query=document.querySelector('#search'),toggle=document.querySelector('.search-toggle');
function expandSearch(expanded){shell.classList.toggle('expanded',expanded);query.disabled=!expanded;toggle.setAttribute('aria-expanded',String(expanded));toggle.setAttribute('aria-label',expanded?'Pesquisar':'Abrir pesquisa');if(expanded)query.focus()}
function submitSearch(){if(!homePage){location.href='index.html?q='+encodeURIComponent(query.value)+'#catalogo';return}document.dispatchEvent(new Event('catalog-search'));document.querySelector('#catalogo').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})}
toggle.onclick=()=>{if(!shell.classList.contains('expanded'))expandSearch(true);else if(query.value.trim())submitSearch();else expandSearch(false)};shell.onsubmit=e=>{e.preventDefault();submitSearch()};query.oninput=()=>{if(homePage)document.dispatchEvent(new Event('catalog-search'))};query.onkeydown=e=>{if(e.key==='Escape'){expandSearch(false);toggle.focus()}};
const personalUrl='https://wa.me/5519983321065?text='+encodeURIComponent('Olá! Gostaria de montar uma cesta personalizada. Podemos conversar sobre as opções?');document.querySelectorAll('.personal-link').forEach(a=>a.href=personalUrl);
document.querySelector('footer').outerHTML=`<footer class="shop-footer"><div class="footer-inner"><a href="${base}#home" aria-label="Voltar ao início"><img src="assets/logo.svg" alt="Logo da loja" width="104" height="42"></a><p>Um gesto de carinho.<br>Uma lembrança especial.</p><div class="footer-social"><a href="https://www.instagram.com/presentebabi/" target="_blank" rel="noopener noreferrer" aria-label="Instagram @presentebabi, abre em nova aba"><span>Instagram · @presentebabi</span>${externalArrowSvg}</a><a href="${personalUrl}"><span>Fale com a gente</span>${externalArrowSvg}</a></div></div><div class="footer-bottom"><span>Cestas e buquês · Feitos sob encomenda</span><span>Pedidos com pelo menos 1 dia de antecedência</span></div></footer>`;
